dist: bionic
language: node_js
node_js: 12

services:
  - docker

before_install:
  - if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then
      export NODE_TAG=master;
      export COMPILER_TAG=latest;
      export FORCE_COMPATIBILITY=true;
    fi
  - docker-compose up -d
